databases:
  - name: journal_app
    plan: free
services:
  - type: web
    name: journal_app
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: journal_app
          property: connectionString
      - key: 4562ae061d84a134e367478940e76824
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
